# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('title_normalized', models.CharField(blank=True, db_column='titleNormalized', max_length=512, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('cover_image', models.JSONField(blank=True, db_column='coverImage', null=True)),
                ('category_slug', models.CharField(blank=True, db_column='categorySlug', max_length=64, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('published', 'published'), ('rejected', 'rejected'), ('approved', 'approved'), ('inactive', 'inactive')], default='draft', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_column='publishedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'blog_articles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogArticleAuthor',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('article', models.ForeignKey(db_column='articleId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='authors_through', to='blog.blogarticle')),
                ('profile', models.ForeignKey(db_column='profileId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_articles_through', to='profiles.profile')),
            ],
            options={
                'db_table': 'blog_article_authors',
                'managed': True,
                'unique_together': {('article', 'profile')},
            },
        ),
    ]
