# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('tagline_normalized', models.TextField(blank=True, db_column='taglineNormalized', null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('bio_normalized', models.TextField(blank=True, db_column='bioNormalized', null=True)),
                ('website', models.URLField(blank=True, max_length=2048, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('speciality', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, db_column='displayName', max_length=255, null=True)),
                ('display_name_normalized', models.CharField(blank=True, db_column='displayNameNormalized', max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('coverage', models.JSONField(blank=True, null=True)),
                ('coverage_normalized', models.TextField(blank=True, db_column='coverageNormalized', null=True)),
                ('image', models.URLField(blank=True, max_length=2048, null=True)),
                ('portfolio', models.JSONField(blank=True, null=True)),
                ('visibility', models.JSONField(blank=True, null=True)),
                ('socials', models.JSONField(blank=True, null=True)),
                ('viber', models.CharField(blank=True, max_length=64, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=64, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('commencement', models.CharField(blank=True, max_length=64, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('contact_methods', models.JSONField(blank=True, db_column='contactMethods', default=list)),
                ('payment_methods', models.JSONField(blank=True, db_column='paymentMethods', default=list)),
                ('settlement_methods', models.JSONField(blank=True, db_column='settlementMethods', default=list)),
                ('budget', models.CharField(blank=True, max_length=64, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('billing', models.JSONField(blank=True, null=True)),
                ('last_service_draft', models.DateTimeField(blank=True, db_column='lastServiceDraft', null=True)),
                ('last_service_refresh_date', models.DateTimeField(blank=True, db_column='lastServiceRefreshDate', null=True)),
                ('daily_service_refresh_count', models.IntegerField(db_column='dailyServiceRefreshCount', default=0)),
                ('author_bio', models.TextField(blank=True, db_column='authorBio', null=True)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(db_column='reviewCount', default=0)),
                ('stars', models.JSONField(blank=True, null=True)),
                ('top', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_column='isActive', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.OneToOneField(db_column='uid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('afm', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('profile', models.OneToOneField(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='verification', related_query_name='verification', to='profiles.profile')),
            ],
            options={
                'db_table': 'verifications',
                'managed': True,
            },
        ),
    ]
