# Generated by Django 5.1.15 on 2026-05-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('title_normalized', models.TextField(blank=True, db_column='titleNormalized', null=True)),
                ('description_normalized', models.TextField(blank=True, db_column='descriptionNormalized', null=True)),
                ('category', models.CharField(max_length=64)),
                ('subcategory', models.CharField(max_length=64)),
                ('subdivision', models.CharField(max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('fixed', models.BooleanField()),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.JSONField()),
                ('subscription_type', models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year'), ('per_case', 'per_case'), ('per_hour', 'per_hour'), ('per_session', 'per_session')], db_column='subscriptionType', max_length=16, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('addons', models.JSONField(blank=True, default=list)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('media', models.JSONField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(db_column='reviewCount', default=0)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('published', 'published'), ('rejected', 'rejected'), ('approved', 'approved'), ('inactive', 'inactive')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('refreshed_at', models.DateTimeField(blank=True, db_column='refreshedAt', null=True)),
                ('sort_date', models.DateTimeField(db_column='sortDate')),
                ('profile', models.ForeignKey(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.profile')),
            ],
            options={
                'db_table': 'services',
                'managed': True,
            },
        ),
    ]
