# Generated by Django 5.1.15 on 2026-06-28 04:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_sortdate_default'),
        ('taxonomy', '0003_alter_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_as_category', to='taxonomy.taxonomynode'),
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory_node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_as_subcategory', to='taxonomy.taxonomynode'),
        ),
        migrations.AddField(
            model_name='service',
            name='subdivision_node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_as_subdivision', to='taxonomy.taxonomynode'),
        ),
    ]
