# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('cid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('last_message_id', models.CharField(blank=True, db_column='lastMessageId', max_length=64, null=True, unique=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True, db_column='lastActivity')),
                ('creator', models.ForeignKey(db_column='creatorUid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='chats_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('message_ids', models.JSONField(db_column='messageIds', default=list)),
                ('message_count', models.IntegerField(db_column='messageCount')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='sentAt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='email_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_batches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='deletedBy', max_length=64, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, db_column='editedAt', null=True)),
                ('reply_to_id', models.CharField(blank=True, db_column='replyToId', max_length=64, null=True)),
                ('reactions', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(db_column='authorUid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages_authored', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(db_column='chatId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chat')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('blocked', models.ForeignKey(db_column='blockedId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(db_column='blockerId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='users_blocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_users',
                'managed': True,
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='joinedAt')),
                ('last_seen', models.DateTimeField(auto_now_add=True, db_column='lastSeen')),
                ('muted', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(db_column='chatId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.chat')),
                ('user', models.ForeignKey(db_column='uid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_members',
                'managed': True,
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
