# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal'), ('eurobank', 'eurobank'), ('worldline', 'worldline'), ('manual', 'manual')], default='stripe', max_length=16)),
                ('provider_customer_id', models.CharField(blank=True, db_column='providerCustomerId', max_length=255, null=True, unique=True)),
                ('provider_subscription_id', models.CharField(blank=True, db_column='providerSubscriptionId', max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_column='stripeCustomerId', max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_column='stripeSubscriptionId', max_length=255, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, db_column='stripePriceId', max_length=255, null=True)),
                ('worldline_token', models.CharField(blank=True, db_column='worldlineToken', max_length=255, null=True)),
                ('worldline_token_exp', models.CharField(blank=True, db_column='worldlineTokenExp', max_length=16, null=True)),
                ('worldline_master_order_id', models.CharField(blank=True, db_column='worldlineMasterOrderId', max_length=255, null=True)),
                ('plan', models.CharField(choices=[('free', 'free'), ('promoted', 'promoted')], default='free', max_length=16)),
                ('status', models.CharField(choices=[('active', 'active'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('incomplete', 'incomplete'), ('trialing', 'trialing'), ('unpaid', 'unpaid')], default='incomplete', max_length=16)),
                ('billing_interval', models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year')], db_column='billingInterval', max_length=8, null=True)),
                ('billing', models.JSONField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, db_column='currentPeriodStart', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_column='currentPeriodEnd', null=True)),
                ('cancel_at_period_end', models.BooleanField(db_column='cancelAtPeriodEnd', default=False)),
                ('canceled_at', models.DateTimeField(blank=True, db_column='canceledAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='eur', max_length=8, null=True)),
                ('payment_method_type', models.CharField(blank=True, db_column='paymentMethodType', max_length=32, null=True)),
                ('payment_method_last4', models.CharField(blank=True, db_column='paymentMethodLast4', max_length=4, null=True)),
                ('payment_method_brand', models.CharField(blank=True, db_column='paymentMethodBrand', max_length=32, null=True)),
                ('total_paid_lifetime', models.IntegerField(db_column='totalPaidLifetime', default=0)),
                ('payment_count', models.IntegerField(db_column='paymentCount', default=0)),
                ('first_payment_at', models.DateTimeField(blank=True, db_column='firstPaymentAt', null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, db_column='lastPaymentAt', null=True)),
                ('discount_code', models.CharField(blank=True, db_column='discountCode', max_length=64, null=True)),
                ('discount_percent_off', models.IntegerField(blank=True, db_column='discountPercentOff', null=True)),
                ('discount_amount_off', models.IntegerField(blank=True, db_column='discountAmountOff', null=True)),
                ('profile', models.OneToOneField(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='profiles.profile')),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': True,
            },
        ),
    ]
