"""Reusable model + view mixins."""
from __future__ import annotations

from django.db import models


class TimestampedMixin(models.Model):
    """Adds Prisma-style createdAt / updatedAt columns.

    Why: every Prisma model in the source has these named exactly `createdAt`
    and `updatedAt`. We map the Python attributes (snake_case) to the
    PostgreSQL columns explicitly so coexistence with the live Next.js writes
    works without renames.
    """

    created_at = models.DateTimeField(auto_now_add=True, db_column="createdAt")
    updated_at = models.DateTimeField(auto_now=True, db_column="updatedAt")

    class Meta:
        abstract = True


class CuidPrimaryKeyMixin(models.Model):
    """String primary key matching Prisma's `cuid()` default.

    Generation happens application-side because Prisma's cuid was generated by
    `@paralleldrive/cuid2`. We keep the column type compatible (text) and
    accept the existing IDs untouched.
    """

    id = models.CharField(max_length=64, primary_key=True, editable=False)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):  # noqa: ANN001, ANN201, D401
        if not self.id:
            from common.utils.cuid import cuid

            self.id = cuid()
        super().save(*args, **kwargs)
