# Generated by Django 5.1.15 on 2026-05-15 08:28

import apps.accounts.models.user
import common.utils.cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jwks',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.TextField(db_column='publicKey')),
                ('private_key', models.TextField(db_column='privateKey')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'jwks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('auth_type', models.IntegerField(db_column='authType')),
                ('role', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, db_column='displayName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
            ],
            options={
                'db_table': 'pending_registrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(db_column='emailVerified', default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('step', models.CharField(choices=[('EMAIL_VERIFICATION', 'EMAIL_VERIFICATION'), ('TYPE_SELECTION', 'TYPE_SELECTION'), ('OAUTH_SETUP', 'OAUTH_SETUP'), ('ONBOARDING', 'ONBOARDING'), ('DASHBOARD', 'DASHBOARD')], default='EMAIL_VERIFICATION', max_length=32)),
                ('confirmed', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('display_username', models.CharField(blank=True, db_column='displayUsername', max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, db_column='displayName', max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('image', models.URLField(blank=True, max_length=2048, null=True)),
                ('ban_expires', models.DateTimeField(blank=True, db_column='banExpires', null=True)),
                ('ban_reason', models.TextField(blank=True, db_column='banReason', null=True)),
                ('banned', models.BooleanField(default=False)),
                ('test_user', models.BooleanField(db_column='testUser', default=False)),
                ('type', models.CharField(choices=[('user', 'user'), ('pro', 'pro')], default='user', max_length=8)),
                ('role', models.CharField(choices=[('user', 'user'), ('freelancer', 'freelancer'), ('company', 'company'), ('admin', 'admin'), ('support', 'support'), ('editor', 'editor')], default='user', max_length=16)),
                ('provider', models.CharField(default='email', max_length=32)),
                ('last_unread_email_sent_at', models.DateTimeField(blank=True, db_column='lastUnreadEmailSentAt', null=True)),
                ('last_username_change_at', models.DateTimeField(blank=True, db_column='lastUsernameChangeAt', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
                'indexes': [models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['step'], name='users_step_b249c0_idx'), models.Index(fields=['confirmed', 'blocked'], name='users_confirm_840244_idx')],
            },
            managers=[
                ('objects', apps.accounts.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, db_column='id_token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('access_token_expires_at', models.DateTimeField(blank=True, db_column='access_token_expires_at', null=True)),
                ('account_id', models.CharField(db_column='accountId', max_length=255, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('provider_id', models.CharField(db_column='providerId', max_length=64)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, db_column='refresh_token_expires_at', null=True)),
                ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', related_query_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('ip_address', models.CharField(blank=True, db_column='ipAddress', max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='userAgent', null=True)),
                ('impersonated_by', models.CharField(blank=True, db_column='impersonatedBy', max_length=64, null=True)),
                ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', related_query_name='session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'verification',
                'managed': True,
                'indexes': [models.Index(fields=['identifier'], name='verificatio_identif_b39f70_idx'), models.Index(fields=['expires_at'], name='verificatio_expires_908aa9_idx')],
            },
        ),
    ]
