# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_column='publicId', max_length=255, unique=True)),
                ('secure_url', models.URLField(db_column='secureUrl', max_length=2048)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=32, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('resource_type', models.CharField(db_column='resourceType', max_length=32)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('original_name', models.CharField(blank=True, db_column='originalName', max_length=512, null=True)),
                ('is_temporary', models.BooleanField(db_column='isTemporary', default=True)),
                ('usage_context', models.CharField(blank=True, db_column='usageContext', max_length=64, null=True)),
                ('usage_id', models.CharField(blank=True, db_column='usageId', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='media', related_query_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media',
                'managed': True,
                'indexes': [models.Index(fields=['public_id'], name='media_publicI_a13851_idx'), models.Index(fields=['is_temporary'], name='media_isTempo_288c9d_idx'), models.Index(fields=['usage_context', 'usage_id'], name='media_usageCo_982eec_idx')],
            },
        ),
    ]
