# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('draft', 'draft'), ('published', 'published'), ('inactive', 'inactive')], default='pending', max_length=16)),
                ('type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('PROFILE', 'PROFILE')], default='PROFILE', max_length=16)),
                ('published', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=False)),
                ('service_id', models.IntegerField(blank=True, db_column='sid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('author', models.ForeignKey(db_column='authorId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='profiles.profile')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
