# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomySubmission',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('skill', 'skill'), ('tag', 'tag')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('submitted_by', models.CharField(db_column='submittedBy', max_length=64)),
                ('reviewed_by', models.CharField(blank=True, db_column='reviewedBy', max_length=64, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewedAt', null=True)),
                ('assigned_id', models.CharField(blank=True, db_column='assignedId', max_length=64, null=True)),
                ('reject_reason', models.TextField(blank=True, db_column='rejectReason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'taxonomy_submissions',
                'managed': True,
            },
        ),
    ]
