# Generated by Django 5.1.15 on 2026-06-28 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_normalized', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'taxonomy_tags',
                'managed': True,
                'indexes': [models.Index(fields=['slug'], name='taxonomy_ta_slug_fb7210_idx'), models.Index(fields=['label_normalized'], name='taxonomy_ta_label_n_0f4bb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyNode',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('space', models.CharField(choices=[('service', 'service'), ('pro', 'pro')], max_length=16)),
                ('level', models.CharField(choices=[('category', 'category'), ('subcategory', 'subcategory'), ('subdivision', 'subdivision')], max_length=16)),
                ('slug', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_normalized', models.CharField(blank=True, default='', max_length=255)),
                ('plural', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.taxonomynode')),
            ],
            options={
                'db_table': 'taxonomy_nodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_normalized', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='taxonomy.taxonomynode')),
            ],
            options={
                'db_table': 'taxonomy_skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('county', 'county'), ('area', 'area'), ('postcode', 'postcode')], default='', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.location')),
            ],
            options={
                'db_table': 'taxonomy_locations',
                'managed': True,
                'indexes': [models.Index(fields=['slug'], name='taxonomy_lo_slug_bd2e5a_idx'), models.Index(fields=['parent'], name='taxonomy_lo_parent__8562ef_idx'), models.Index(fields=['name_normalized'], name='taxonomy_lo_name_no_93a458_idx'), models.Index(fields=['type'], name='taxonomy_lo_type_73242a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['space', 'level'], name='taxonomy_no_space_9e48b6_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['space', 'level', 'slug'], name='taxonomy_no_space_120008_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['slug'], name='taxonomy_no_slug_673944_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['parent'], name='taxonomy_no_parent__a14c72_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['label_normalized'], name='taxonomy_no_label_n_a832f5_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['slug'], name='taxonomy_sk_slug_0a3154_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='taxonomy_sk_categor_4628a2_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['label_normalized'], name='taxonomy_sk_label_n_e8a7cf_idx'),
        ),
    ]
