# Generated by Django 5.1.15 on 2026-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_tag_taxonomynode_skill_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('place', 'place'), ('postcode', 'postcode'), ('county', 'county'), ('area', 'area')], default='', max_length=16),
        ),
    ]
