# Generated by Django 5.1.15 on 2026-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_alter_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='slug_primary',
            field=models.BooleanField(default=True),
        ),
    ]
