# Generated by Django 5.1.15 on 2026-06-28 08:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_location_slug_primary_taxonomynode_slug_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
