# Generated by Django 5.1.15 on 2026-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_location_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTree',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('tree', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'taxonomy_location_tree',
                'managed': True,
            },
        ),
    ]
