# Generated by Django 5.1.15 on 2026-05-15 08:28

import common.utils.cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=common.utils.cuid.cuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'contacts',
                'managed': True,
            },
        ),
    ]
