/**
 * Prisma compatibility shim.
 *
 * The Prisma client is no longer in the runtime bundle (Django owns DB
 * writes), but lots of components still import enum values + types from
 * `@prisma/client`. This shim exposes the same names with the same string
 * values, so the rest of the codebase doesn't have to change.
 *
 * If you're writing new code, prefer importing string literals or use the
 * Django REST payloads directly.
 */

// ---- Enum values (used at runtime, e.g. SubscriptionStatus.active) -------

export const UserRole = {
  user: 'user',
  freelancer: 'freelancer',
  company: 'company',
  admin: 'admin',
  support: 'support',
  editor: 'editor',
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserType = {
  user: 'user',
  pro: 'pro',
} as const;
export type UserType = (typeof UserType)[keyof typeof UserType];

export const JourneyStep = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  TYPE_SELECTION: 'TYPE_SELECTION',
  OAUTH_SETUP: 'OAUTH_SETUP',
  ONBOARDING: 'ONBOARDING',
  DASHBOARD: 'DASHBOARD',
} as const;
export type JourneyStep = (typeof JourneyStep)[keyof typeof JourneyStep];

export const Status = {
  draft: 'draft',
  pending: 'pending',
  published: 'published',
  rejected: 'rejected',
  approved: 'approved',
  inactive: 'inactive',
} as const;
export type Status = (typeof Status)[keyof typeof Status];

export const SubscriptionType = {
  month: 'month',
  year: 'year',
  per_case: 'per_case',
  per_hour: 'per_hour',
  per_session: 'per_session',
} as const;
export type SubscriptionType = (typeof SubscriptionType)[keyof typeof SubscriptionType];

export const SubscriptionStatus = {
  active: 'active',
  past_due: 'past_due',
  canceled: 'canceled',
  incomplete: 'incomplete',
  trialing: 'trialing',
  unpaid: 'unpaid',
} as const;
export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

export const SubscriptionPlan = {
  free: 'free',
  promoted: 'promoted',
} as const;
export type SubscriptionPlan = (typeof SubscriptionPlan)[keyof typeof SubscriptionPlan];

export const BillingInterval = {
  month: 'month',
  year: 'year',
} as const;
export type BillingInterval = (typeof BillingInterval)[keyof typeof BillingInterval];

export const SubscriptionProvider = {
  stripe: 'stripe',
  paypal: 'paypal',
  eurobank: 'eurobank',
  worldline: 'worldline',
  manual: 'manual',
} as const;
export type SubscriptionProvider = (typeof SubscriptionProvider)[keyof typeof SubscriptionProvider];

export const ReviewType = {
  SERVICE: 'SERVICE',
  PROFILE: 'PROFILE',
} as const;
export type ReviewType = (typeof ReviewType)[keyof typeof ReviewType];

export const TaxonomySubmissionType = {
  skill: 'skill',
  tag: 'tag',
} as const;
export type TaxonomySubmissionType = (typeof TaxonomySubmissionType)[keyof typeof TaxonomySubmissionType];

export const TaxonomySubmissionStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;
export type TaxonomySubmissionStatus = (typeof TaxonomySubmissionStatus)[keyof typeof TaxonomySubmissionStatus];

// ---- Loose type aliases used by existing components (record-shaped) ------
// These mirror the keys our Django serializers return.
//
// JSON columns are typed via the global `AppJson` namespace
// (see `src/lib/prisma/json-types.ts`) — these are the same types the old
// `prisma-json-types-generator` produced from the schema's `/// [Type]`
// annotations, just declared by the app instead of generated by Prisma.

export interface User {
  id: string;
  email: string;
  emailVerified: boolean;
  name: string | null;
  username: string | null;
  displayName: string | null;
  firstName: string | null;
  lastName: string | null;
  image: string | null;
  step: JourneyStep;
  role: UserRole;
  type: UserType;
  confirmed: boolean;
  blocked: boolean;
  banned: boolean;
  banReason: string | null;
  banExpires: string | null;
  provider: string;
  testUser?: boolean;
  createdAt: string;
  updatedAt?: string;
  lastUnreadEmailSentAt?: string | null;
  lastUsernameChangeAt?: string | null;
}

export interface Profile {
  id: string;
  uid: string;
  type: string | null;
  username: string | null;
  displayName: string | null;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  phone: string | null;
  tagline: string | null;
  bio: string | null;
  website: string | null;
  size: string | null;
  category: string | null;
  subcategory: string | null;
  speciality: string | null;
  skills: string[];
  coverage: AppJson.Coverage | null;
  portfolio: AppJson.Portfolio | null;
  visibility: AppJson.VisibilitySettings | null;
  socials: AppJson.SocialMedia | null;
  viber: string | null;
  whatsapp: string | null;
  rate: number | null;
  commencement: string | null;
  experience: number | null;
  contactMethods: string[];
  paymentMethods: string[];
  settlementMethods: string[];
  budget: string | null;
  terms: string | null;
  billing: AppJson.BillingInfo | null;
  image: string | null;
  authorBio: string | null;
  verified: boolean;
  featured: boolean;
  rating: number;
  reviewCount: number;
  stars: AppJson.StarBreakdown | null;
  top: boolean;
  published: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Service {
  id: number;
  pid: string;
  slug: string | null;
  title: string;
  description: string;
  category: string;
  subcategory: string;
  subdivision: string;
  tags: string[];
  fixed: boolean;
  price: number | null;
  type: AppJson.ServiceType | null;
  subscriptionType: SubscriptionType | null;
  duration: number | null;
  addons: AppJson.ServiceAddon[];
  faq: AppJson.ServiceFAQ[];
  media: AppJson.Media | null;
  featured: boolean;
  rating: number;
  reviewCount: number;
  status: Status;
  createdAt: string;
  updatedAt: string;
  refreshedAt: string | null;
  sortDate: string;
}

export interface Subscription {
  id: string;
  pid: string;
  provider: SubscriptionProvider;
  plan: SubscriptionPlan;
  status: SubscriptionStatus;
  billingInterval: BillingInterval | null;
  amount: number | null;
  currency: string | null;
  cancelAtPeriodEnd: boolean;
  canceledAt: string | null;
  currentPeriodEnd: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Review {
  id: string;
  rating: number;
  comment: string | null;
  status: Status;
  type: ReviewType;
  published: boolean;
  visibility: boolean;
  pid: string;
  sid: number | null;
  authorId: string;
  createdAt: string;
  updatedAt: string;
}

export interface BlogArticle {
  id: string;
  slug: string;
  title: string;
  excerpt: string | null;
  content: string;
  coverImage: AppJson.CloudinaryResource | null;
  categorySlug: string | null;
  status: Status;
  featured: boolean;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}
